import type { FullConfig } from "./config-schema";

export type FlatConfigState = {
  architecture: FullConfig["architecture"];
  networkMode: FullConfig["networkMode"];
} & FullConfig["monerod"]
  & FullConfig["stagenet"]
  & FullConfig["p2pool"]
  & FullConfig["mining"]
  & FullConfig["tor"]
  & FullConfig["services"];

export function toFullConfig(state: FlatConfigState): FullConfig {
  return {
    architecture: state.architecture,
    networkMode: state.networkMode,
    monerod: {
      isMoneroPublicNode: state.isMoneroPublicNode,
      moneroNodeNoLogs: state.moneroNodeNoLogs,
      moneroNodeDomain: state.moneroNodeDomain,
      isPrunedNode: state.isPrunedNode,
      isSyncPrunedBlocks: state.isSyncPrunedBlocks,
      isMoneroMainnetVolume: state.isMoneroMainnetVolume,
      moneroMainnetBlockchainLocation: state.moneroMainnetBlockchainLocation,
      logLevel: state.logLevel,
      maxLogFileSize: state.maxLogFileSize,
      maxLogFiles: state.maxLogFiles,
      p2pBindPort: state.p2pBindPort,
      outPeers: state.outPeers,
      inPeers: state.inPeers,
      limitRateUp: state.limitRateUp,
      limitRateDown: state.limitRateDown,
      hidePort: state.hidePort,
      allowLocalIp: state.allowLocalIp,
      maxConnectionsPerIp: state.maxConnectionsPerIp,
      p2pExternalPort: state.p2pExternalPort,
      offlineMode: state.offlineMode,
      padTransactions: state.padTransactions,
      anonymousInbound: state.anonymousInbound,
      txProxyDisableNoise: state.txProxyDisableNoise,
      banList: state.banList,
      enableDnsBlocklist: state.enableDnsBlocklist,
      dnsCheckpoints: state.dnsCheckpoints,
      seedNode: state.seedNode,
      addPeer: state.addPeer,
      addPriorityNode: state.addPriorityNode,
      addExclusiveNode: state.addExclusiveNode,
      dbSyncMode: state.dbSyncMode,
      blockSyncSize: state.blockSyncSize,
      fastBlockSync: state.fastBlockSync,
      preparationThreads: state.preparationThreads,
      maxConcurrency: state.maxConcurrency,
      bootstrapDaemonAddress: state.bootstrapDaemonAddress,
      bootstrapDaemonLogin: state.bootstrapDaemonLogin,
      zmqPubEnabled: state.zmqPubEnabled,
      zmqPubBindPort: state.zmqPubBindPort,
      rpcLogin: state.rpcLogin,
      disableRpcBan: state.disableRpcBan,
      maxTxpoolWeight: state.maxTxpoolWeight,
      startMining: state.startMining,
      miningThreads: state.miningThreads,
      bgMiningEnable: state.bgMiningEnable,
      bgMiningIgnoreBattery: state.bgMiningIgnoreBattery,
      blockNotify: state.blockNotify,
      reorgNotify: state.reorgNotify,
      blockRateNotify: state.blockRateNotify,
    },
    stagenet: {
      isStagenetNode: state.isStagenetNode,
      isStagenetNodePublic: state.isStagenetNodePublic,
      isMoneroStagenetCustomLocation: state.isMoneroStagenetCustomLocation,
      moneroStagenetBlockchainLocation: state.moneroStagenetBlockchainLocation,
      stagenetNodeDomain: state.stagenetNodeDomain,
    },
    p2pool: {
      p2PoolMode: state.p2PoolMode,
      p2PoolPayoutAddress: state.p2PoolPayoutAddress,
      p2PoolMiningThreads: state.p2PoolMiningThreads,
      isP2PoolStratumPublic: state.isP2PoolStratumPublic,
    },
    mining: {
      miningMode: state.miningMode,
      xmrigDonateLevel: state.xmrigDonateLevel,
    },
    tor: {
      torProxyMode: state.torProxyMode,
      hsMonerod: state.hsMonerod,
      hsMonerodP2P: state.hsMonerodP2P,
      hsStagenet: state.hsStagenet,
      hsP2Pool: state.hsP2Pool,
      hsGrafana: state.hsGrafana,
      hsLws: state.hsLws,
      hsMoneroPay: state.hsMoneroPay,
      hsXmrigProxy: state.hsXmrigProxy,
      isGlobalTorProxy: state.isGlobalTorProxy,
    },
    services: {
      isMoneroWalletRpc: state.isMoneroWalletRpc,
      isWatchtower: state.isWatchtower,
      isMonitoring: state.isMonitoring,
      grafanaDomain: state.grafanaDomain,
      isTraefik: state.isTraefik,
      isTraefikMonerod: state.isTraefikMonerod,
      isTraefikStagenet: state.isTraefikStagenet,
      isTraefikGrafana: state.isTraefikGrafana,
      isTraefikPortainer: state.isTraefikPortainer,
      isPortainer: state.isPortainer,
      portainerDomain: state.portainerDomain,
      isCuprateEnabled: state.isCuprateEnabled,
      isMoneroLws: state.isMoneroLws,
      isMoneroPay: state.isMoneroPay,
      isXmrigProxy: state.isXmrigProxy,
      isXmrigProxyPublic: state.isXmrigProxyPublic,
      isTraefikLws: state.isTraefikLws,
      isTraefikMoneroPay: state.isTraefikMoneroPay,
      lwsDomain: state.lwsDomain,
      moneroPayDomain: state.moneroPayDomain,
    },
    enabledBashServices: {
      monitoring: state.isMonitoring,
      cuprate: state.isCuprateEnabled,
    },
  };
}
