onlyBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - next
  - "@next/*"
  - react
  - react-dom
  - "@vercel/*"
  - "@types/react"
  - "@types/node"